# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/201-web-app-custom-domain-and-ssl' 
    artifactName: '201-web-app-custom-domain-and-ssl'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/101-key-vault-create' 
    artifactName: '101-key-vault-create'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/101-keyvault-add-access-policy' 
    artifactName: '101-keyvault-add-access-policy'